FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN pip install uv
RUN uv sync --frozen

COPY manage.py ./
COPY tarefas/ ./tarefas/
COPY todo/ ./todo/

EXPOSE 8000

CMD sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 tarefas.wsgi:application"
