FROM python:3.13-slim

WORKDIR /app

# 1. Copia SÓ os arquivos de dependência
COPY pyproject.toml uv.lock ./

# ----------------------------------------------------
# 2. Instala o UV e as dependências (Django, Gunicorn, etc.)
RUN pip install uv
RUN uv sync --frozen --system

# 3. Copia o resto do seu código
COPY manage.py ./
COPY tarefas/ ./tarefas/
COPY todo/ ./todo/

# 4. Roda o collectstatic
# (Agora vai funcionar, porque o Django foi instalado no passo 2)
RUN python manage.py collectstatic --noinput

EXPOSE 8000

# 5. Roda o migrate e inicia o servidor Gunicorn
CMD sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 tarefas.wsgi:application"
