# Generated by Django 5.2.7 on 2025-11-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_options_task_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'created_date']},
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', '🟢 Baixa'), ('medium', '🟡 Média'), ('high', '🔴 Alta'), ('urgent', '⚡ Urgente')], default='medium', max_length=200),
        ),
    ]
